# Google Drive
google.drive.client.email=${GOOGLE_DRIVE_CLIENT_EMAIL}
google.drive.client.id=${GOOGLE_DRIVE_CLIENT_ID}
google.drive.private.key.id=${GOOGLE_DRIVE_PRIVATE_KEY_ID}
google.drive.private.key=${GOOGLE_DRIVE_PRIVATE_KEY_PKCS8}
# Media folders
movies.folder=${MOVIES_FOLDER}
shows.folder=${SHOWS_FOLDER}
# Postgres
zplex.db.host=${ZPLEX_DATABASE_HOST}
zplex.db.port=${ZPLEX_DATABASE_PORT}
zplex.db.username=${ZPLEX_DATABASE_USERNAME}
zplex.db.password=${ZPLEX_DATABASE_PASSWORD}
# Valkey
zplex.cache.host=${ZPLEX_CACHE_HOST}
zplex.cache.port=${ZPLEX_CACHE_PORT}
zplex.cache.username=${ZPLEX_CACHE_USERNAME}
zplex.cache.password=${ZPLEX_CACHE_PASSWORD}
# Metadata sources
omdb.api.key=${OMDB_API_KEY}
tmdb.api.key=${TMDB_API_KEY}